kayunkim/lectures/WEB/Django/practice/0421/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/comments', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
]

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.CharField(max_length=100)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method=='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.save()
    return redirect('articles:detail', article_pk)

def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
	<h2>DETAIL</h2>
	<hr>
	<h3>{{ article.pk }}번글</h3>
	<p>제목: {{ article.title }}</p>
	<p>내용: {{ article.content }}</p>
	<p>생성 시각: {{ article.created_at }}</p>
	<p>수정 시각: {{ article.updated_at }}</p>
	<a href="{% url 'articles:index' %}">BACK</a>

	<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
		{% csrf_token %}
		{{ comment_form.as_p }}
		<button>댓글작성</button>
	</form>

	<h3>댓글 목록</h3>
	<h3>{{ article.title }}</h3>
	{% for comment in article.comment_set.all %}
		<p>{{ comment.content }}</p>
		<a href="{% url 'articles:comment_delete' article.pk comment.pk %}">댓글삭제</a>
	{% empty %}
		<p>댓글이 없습니다.</p>
	{% endfor %}

{% endblock %}

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
	<h2>CREATE</h2>
	<hr>
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button>Submit</button>
	</form>
	<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

kayunkim/lectures/WEB/Django/practice/0421/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
	<h2>INDEX</h2>
	<a href="{% url 'articles:create' %}">CREATE</a>
	<hr>
	{% for article in articles %}
		<h3>
			<ul>
				<li>{{ article.pk }}</li>
				<li><a href="{% url 'articles:detail' article.pk%}">{{ article.title }}</a></li>
			</ul>
		</h3>
	{% endfor %}
{% endblock %}