kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('<int:user_pk>/delete/', views.delete_user, name='delete_user'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/detail/', views.detail, name='detail'),
]

kayunkim/lectures/WEB/Django/project/Django_PJT3/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('review_create/', views.review_create, name='review_create'),
    path('<int:review_pk>/detail/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),

]

kayunkim/lectures/WEB/Django/project/Django_PJT3/django_pjt3/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
]

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/models.py
from django.db import models

# Create your models here.

kayunkim/lectures/WEB/Django/project/Django_PJT3/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


# Create your views here.
def index(request):
    User = get_user_model()
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    else:
        if request.method=='POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('community:index')
        else:
            form = UserCreationForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    else:
        if request.method=='POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect(request.GET.get('next') or 'community:index')
        else:
            form = AuthenticationForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/login.html', context)

@require_POST
@login_required
def logout(request):
    auth_logout(request)
    return redirect('community:index')

@require_POST
@login_required
def delete_user(request, user_pk):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)
    if user == request.user:
        user.delete()
    return redirect('accounts:signup')

def detail(request, user_pk):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/templates/accounts/detail.html
{% extends 'base.html' %}


{% block content %}
<h1>{{ user.username }}</h1>
<hr>
<h1 class='text-center'>작성한 글 목록</h1>
<hr>
<table class="table">
  <thead class="thead-dark table-striped">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Movie Title</th>
    </tr>
  </thead>
  <tbody>
{% for review in user.review_set.all %}
    <tr>
      <th scope="row">{{ review.pk }}</th>
      <td><a href="{% url 'community:review_detail' review.pk %}">{{ review.title }}</a></td>
      <td>{{ review.movie_title }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
<form action="{% url 'accounts:delete_user' user.pk %}" method="POST">
    {% csrf_token %}
    <button class='btn btn-danger'>계정탈퇴</button>
</form>
{% endblock %}

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/templates/accounts/index.html
{% extends 'base.html' %}
<h1>index</h1>
{% block content %}
    <h1>회원 목록</h1>
    {% for user in users %}
        <h3> {{ user.pk }} : {{ user.username }}</h3>
        {% if user == request.user %}
        <a href="{% url 'accounts:delete_user' user.pk %}">회원 탈퇴</a>
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<h1>로그인 페이지</h1>
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-primary'>로그인</button>
    </form>
{% endblock %}

kayunkim/lectures/WEB/Django/project/Django_PJT3/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<h1>회원가입 페이지</h1>
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-primary'>회원가입</button>
    </form>
{% endblock %}