kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#상속=>custom
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  #accounts.User
        fields= ['username',]

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email']

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def profile(request, username):
    User = get_user_model()
    profile_owner = get_object_or_404(User, username=username)   # 프린트하면, 내부적으로 username이 출력됨
    context = {
        'profile_owner':profile_owner,
    }
    return render(request,'accounts/profile.html', context)

@login_required
def follow(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    if request.user != user:
        # if request.user in followers.all():
        if user.followers.filter(pk=request.user.pk).exists():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
    return redirect('accounts:profile', username)

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>LOGIN</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ profile_owner }}님의 PROFILE</h2>
  {% if request.user != profile_owner %}
      {% if request.user in profile_owner.followers.all %}
          <a href="{% url 'accounts:follow' profile_owner %}"><button>UNFOLLOW</button></a>
      {% else %}
          <a href="{% url 'accounts:follow' profile_owner %}"><button>FOLLOW</button></a>
      {% endif %}
  {% endif %}
  <!--<p>{{ profile_owner.article_set.count }} posts</p>-->
  <p>{{ profile_owner.article_set.all|length }} posts</p>
  <p>{{ profile_owner.followers.all|length }} followers</p>
  <p>{{ profile_owner.followings.all|length }} following </p>
  {% for article in profile_owner.article_set.all %}
    <p>{{ article.title }}:{{ article.content }}</p>
  {% endfor %}
  <p>{{ profile}}</p>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

kayunkim/lectures/WEB/Django/practice/0428/workshop/crud/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>SIGNUP</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}